### PR TITLE
Migrate avalonia to v11

### PR DESCRIPTION
**Pull request by rstm-sf**

### CODE REVIEW

**Comment by ForNeVeR** [comment]
This is all good. The only thing I'd like to do is to wait intil the Avalonia 11 release. I hesitate a bit to publish a release version of package relying on a pre-release dependency.

**Comment by ForNeVeR** [comment]
Is it ready for review & merge?

**Comment by JohanMilter** [comment]
> Is it ready for review & merge?

Hi. Thank you a lot for the AvaloniaMath and XamlMath library! I think Avalonia v11 isnt a prerelease anymore. I have a project im working on, and when i go to nuget package manager it says, that i can now update to Avalonia v11 and not the prerelease. Is it possible to get the AvaloniaMath for Avalonia v11 now; if not when is it possible? Again thanks for the library! 

Best regards
Johan

**Comment by ForNeVeR** [comment]
I currently plan to start work on this on 2023-07-14, if @rstm-sf doesn't finish this earlier :)

**Comment by ForNeVeR** [comment]
>Highlights https://github.com/AvaloniaUI/Avalonia/issues/11802

So, this is a problem of our example app and not of the library, right?

**Review by ForNeVeR — APPROVED** [review]
Great, thanks a lot!

**Comment by ForNeVeR** [comment]
I am planning to release a new version tomorrow.

**Pull request merged**
